-- MySQL Script generated by MySQL Workbench
-- Tue Oct  8 21:41:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_funcao` (
  `id_funcao` INT NOT NULL,
  PRIMARY KEY (`id_funcao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_funcionarios` (
  `id_funcionarios` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `matricula` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_funcao` INT NOT NULL,
  PRIMARY KEY (`id_funcionarios`, `id_funcao`),
  CONSTRAINT `fk_tb_funcionarios_tb_funcao1`
    FOREIGN KEY (`id_funcao`)
    REFERENCES `mydb`.`tb_funcao` (`id_funcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_horarios` (
  `id_horario` INT NOT NULL,
  `horario` TIME NOT NULL,
  `turno` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_cursos` (
  `id_curso` INT NOT NULL,
  `nome_curso` VARCHAR(45) NOT NULL,
  `sigla_curso` VARCHAR(45) NOT NULL,
  `id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  CONSTRAINT `id_disciplina`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `mydb`.`tb_disciplina` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_disciplina` (
  `id_disciplina` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `semestre` INT NOT NULL,
  `horas_aula` VARCHAR(45) NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`, `id_curso`),
  CONSTRAINT `fk_tb_disciplina_tb_cursos1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`tb_cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_funcionarios_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_funcionarios_cursos` (
  `id_funcionarios` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_funcionarios`, `id_curso`),
  CONSTRAINT `fk_tb_funcionarios_has_tb_cursos_tb_funcionarios1`
    FOREIGN KEY (`id_funcionarios`)
    REFERENCES `mydb`.`tb_funcionarios` (`id_funcionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_funcionarios_has_tb_cursos_tb_cursos1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `mydb`.`tb_cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_disciplina_horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_disciplina_horarios` (
  `id_disciplina` INT NOT NULL,
  `id_horario` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`, `id_horario`),
  CONSTRAINT `fk_tb_disciplina_has_tb_horarios_tb_disciplina1`
    FOREIGN KEY (`id_disciplina`)
    REFERENCES `mydb`.`tb_disciplina` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_disciplina_has_tb_horarios_tb_horarios1`
    FOREIGN KEY (`id_horario`)
    REFERENCES `mydb`.`tb_horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_categoria` (
  `id_categoria` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_motivo_faltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_motivo_faltas` (
  `id_motivo` INT NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_motivo`, `id_categoria`),
  CONSTRAINT `fk_tb_motivo_faltas_tb_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`tb_categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_justificativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_justificativas` (
  `id_justificativa` INT NOT NULL,
  `id_motivo` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_justificativa`, `id_motivo`, `id_categoria`),
  CONSTRAINT `fk_tb_justificativas_tb_motivo_faltas1`
    FOREIGN KEY (`id_motivo` , `id_categoria`)
    REFERENCES `mydb`.`tb_motivo_faltas` (`id_motivo` , `id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_documentos` (
  `id_arquivo` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_arquivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_funcionarios_cursos_disciplina_horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_funcionarios_cursos_disciplina_horarios` (
  `id_funcionarios` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `id_horario` INT NOT NULL,
  PRIMARY KEY (`id_funcionarios`, `id_curso`, `id_disciplina`, `id_horario`),
	CONSTRAINT `fk_tb_funcionarios_has_tb_cursos_has_tb_disciplina_has_tb_hor1`
    FOREIGN KEY (`id_funcionarios` , `id_curso`)
    REFERENCES `mydb`.`tb_funcionarios_cursos` (`id_funcionarios` , `id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_funcionarios_has_tb_cursos_has_tb_disciplina_has_tb_hor2`
    FOREIGN KEY (`id_disciplina` , `id_horario`)
    REFERENCES `mydb`.`tb_disciplina_horarios` (`id_disciplina` , `id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_status_coordenacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_status_coordenacao` (
  `id_status` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_requisicao` (
  `id_requisicao` INT NOT NULL,
  `coment_requisicao` VARCHAR(45) NOT NULL,
  `confirmado` VARCHAR(45) NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_requisicao`, `id_status`),
   CONSTRAINT `fk_tb_requisicao_tb_status_coordenacao1`
    FOREIGN KEY (`id_status`)
    REFERENCES `mydb`.`tb_status_coordenacao` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_nova_requisicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_nova_requisicao` (
  `id_requisicao` INT NOT NULL,
  `id_justificativa` INT NOT NULL,
  `id_arquivo` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `id_disciplina` INT NOT NULL,
  `id_horario` INT NOT NULL,
  `data_inicial_falta` VARCHAR(45) NOT NULL,
  `data_final_falta` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(500) NOT NULL,
  `data_inicial_reposicao` VARCHAR(45) NOT NULL,
  `data_final_reposicao` VARCHAR(45) NOT NULL,
  `confirmar_reposicao` VARCHAR(45) NOT NULL,
  `id_requisicao` INT NOT NULL,
  `id_status` INT NOT NULL,
  PRIMARY KEY (`id_requisicao`, `id_justificativa`, `id_arquivo`, `id_funcionario`, `id_curso`, `id_disciplina`, `id_horario`, `id_requisicao`, `id_status`),
   CONSTRAINT `fk_tb_nova_requisicao_tb_justificativas1`
    FOREIGN KEY (`id_justificativa`)
    REFERENCES `mydb`.`tb_justificativas` (`id_justificativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_nova_requisicao_tb_documentos1`
    FOREIGN KEY (`id_arquivo`)
    REFERENCES `mydb`.`tb_documentos` (`id_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_nova_requisicao_tb_funcionarios_cursos_disciplina_horar1`
    FOREIGN KEY (`id_funcionario` , `id_curso` , `id_disciplina` , `id_horario`)
    REFERENCES `mydb`.`tb_funcionarios_cursos_disciplina_horarios` (`id_funcionarios` , `id_curso` , `id_disciplina` , `id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_nova_requisicao_tb_requisicao1`
    FOREIGN KEY (`id_requisicao` , `id_status`)
    REFERENCES `mydb`.`tb_requisicao` (`id_requisicao` , `id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_rela_pdf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_rela_pdf` (
  `id_relatorio` INT NOT NULL,
  `id_requisicao` INT NOT NULL,
  PRIMARY KEY (`id_relatorio`, `id_requisicao`),
   CONSTRAINT `fk_tb_rela_pdf_tb_nova_requisicao1`
    FOREIGN KEY (`id_requisicao`)
    REFERENCES `mydb`.`tb_nova_requisicao` (`id_requisicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
